/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatThread {
  'id' : string,
  'is_blocked' : boolean,
  'is_muted' : boolean,
  'messages' : Array<Message>,
  'typing_buyer' : boolean,
  'seller' : Principal,
  'typing_seller' : boolean,
  'buyer' : Principal,
  'listing_id' : string,
}
export type ExternalBlob = Uint8Array;
export interface InsightsAnalytics {
  'mostPopularCategory' : [] | [string],
  'mostTradedCategory' : [] | [MostTradedCategoryAnalytics],
}
export interface Listing {
  'id' : string,
  'status' : ListingStatus,
  'title' : string,
  'updated_at' : Time,
  'description' : string,
  'created_at' : Time,
  'seller' : Principal,
  'category' : string,
  'campus' : string,
  'department' : string,
  'price' : number,
  'hostel' : string,
  'condition' : string,
  'images' : Array<ListingImage>,
}
export interface ListingImage {
  'id' : bigint,
  'url' : string,
  'upload_status' : string,
  'blob' : [] | [ExternalBlob],
  'name' : string,
}
export type ListingStatus = { 'active' : null } |
  { 'sold' : null } |
  { 'draft' : null };
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'read_by_seller' : boolean,
  'read_by_buyer' : boolean,
  'timestamp' : Time,
}
export interface MostTradedCategoryAnalytics {
  'topItems' : Array<[string, bigint]>,
  'sales' : bigint,
  'category' : string,
}
export interface Notification {
  'id' : string,
  'is_read' : boolean,
  'user' : Principal,
  'timestamp' : Time,
  'notif_type' : NotificationType,
}
export type NotificationType = { 'listing_sold' : { 'listing_id' : string } } |
  { 'new_message' : { 'listing_id' : string } } |
  { 'price_change' : { 'listing_id' : string } } |
  { 'systemNotification' : {} };
export type RecommendationMode = { 'heuristic' : null } |
  { 'external' : null };
export interface RecommendationRequest {
  'recType' : RecommendationType,
  'user' : Principal,
  'limit' : bigint,
  'externalPrompt' : [] | [string],
  'contextListing' : [] | [Listing],
}
export interface RecommendationResponse {
  'recType' : RecommendationType,
  'source' : RecommendationMode,
  'listings' : Array<Listing>,
}
export type RecommendationType = { 'similarCategory' : null } |
  { 'trending' : null } |
  { 'collaborative' : null } |
  { 'personalized' : null };
export interface Report {
  'id' : string,
  'timestamp' : Time,
  'listing_id' : string,
  'reporter' : Principal,
  'reason' : string,
}
export interface SellWizardDraft {
  'id' : string,
  'title' : string,
  'updated_at' : Time,
  'description' : string,
  'created_at' : Time,
  'category' : string,
  'campus' : string,
  'department' : string,
  'price' : number,
  'hostel' : string,
  'condition' : string,
  'images' : Array<ListingImage>,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'onboarding_complete' : boolean,
  'campus' : string,
  'department' : string,
  'hostel' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addListing' : ActorMethod<[Listing], undefined>,
  'addMessage' : ActorMethod<[string, Message], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatThread' : ActorMethod<[ChatThread], undefined>,
  'createReport' : ActorMethod<[Report], undefined>,
  'deleteDraft' : ActorMethod<[string], undefined>,
  'deleteListing' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'fetchRecommendations' : ActorMethod<
    [RecommendationRequest],
    RecommendationResponse
  >,
  'getAIRecommendationMode' : ActorMethod<[], RecommendationMode>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatThread' : ActorMethod<[string], [] | [ChatThread]>,
  'getChatThreads' : ActorMethod<[], Array<ChatThread>>,
  'getDraft' : ActorMethod<[string], [] | [SellWizardDraft]>,
  'getDrafts' : ActorMethod<[], Array<SellWizardDraft>>,
  'getInsightsAnalytics' : ActorMethod<[], InsightsAnalytics>,
  'getListing' : ActorMethod<[string], [] | [Listing]>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<Listing>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPersistentStorageCount' : ActorMethod<[], bigint>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getSavedListings' : ActorMethod<[], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAIAssistEnabled' : ActorMethod<[], boolean>,
  'isAIFeatureEnabled' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraft' : ActorMethod<[SellWizardDraft], undefined>,
  'saveListing' : ActorMethod<[string], undefined>,
  'searchListings' : ActorMethod<[string], Array<Listing>>,
  'setAIFeatureEnabled' : ActorMethod<[boolean], undefined>,
  'setRecommendationMode' : ActorMethod<[RecommendationMode], undefined>,
  'unsaveListing' : ActorMethod<[string], undefined>,
  'updateListing' : ActorMethod<[string, Listing], undefined>,
  'updateTypingStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];