/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'sold' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const SellerTrustIndicators = IDL.Record({
  'verified_student' : IDL.Bool,
  'star_rating' : IDL.Float64,
  'reliability_score' : IDL.Float64,
  'transaction_count' : IDL.Nat,
});
export const LocationDetail = IDL.Record({
  'name' : IDL.Text,
  'location_type' : IDL.Variant({
    'dorm' : IDL.Null,
    'zone' : IDL.Null,
    'building' : IDL.Null,
    'meetupSpot' : IDL.Null,
  }),
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const ProductCondition = IDL.Variant({
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'likeNew' : IDL.Null,
  'wellUsed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingImage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'upload_status' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'updated_at' : Time,
  'trust_indicators' : SellerTrustIndicators,
  'description' : IDL.Text,
  'created_at' : Time,
  'seller' : IDL.Principal,
  'meetup_locations' : IDL.Vec(LocationDetail),
  'defect_description' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'campus' : IDL.Text,
  'department' : IDL.Text,
  'original_price' : IDL.Opt(IDL.Nat32),
  'price' : IDL.Nat32,
  'hostel' : IDL.Text,
  'condition' : ProductCondition,
  'images' : IDL.Vec(ListingImage),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'read_by_seller' : IDL.Bool,
  'read_by_buyer' : IDL.Bool,
  'timestamp' : Time,
});
export const Review = IDL.Record({
  'created_at' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatThread = IDL.Record({
  'id' : IDL.Text,
  'is_blocked' : IDL.Bool,
  'is_muted' : IDL.Bool,
  'messages' : IDL.Vec(Message),
  'typing_buyer' : IDL.Bool,
  'seller' : IDL.Principal,
  'typing_seller' : IDL.Bool,
  'buyer' : IDL.Principal,
  'listing_id' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'timestamp' : Time,
  'listing_id' : IDL.Text,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});
export const RecommendationType = IDL.Variant({
  'similarCategory' : IDL.Null,
  'trending' : IDL.Null,
  'collaborative' : IDL.Null,
  'personalized' : IDL.Null,
});
export const RecommendationRequest = IDL.Record({
  'recType' : RecommendationType,
  'user' : IDL.Principal,
  'limit' : IDL.Nat,
  'externalPrompt' : IDL.Opt(IDL.Text),
  'contextListing' : IDL.Opt(Listing),
});
export const PriceRange = IDL.Record({ 'max' : IDL.Nat32, 'min' : IDL.Nat32 });
export const ListingSortOption = IDL.Variant({
  'none' : IDL.Null,
  'priceLowToHigh' : IDL.Null,
  'distance' : IDL.Null,
  'newestFirst' : IDL.Null,
  'relevance' : IDL.Null,
  'priceHighToLow' : IDL.Null,
  'conditionQuality' : IDL.Null,
  'popularity' : IDL.Null,
});
export const SearchCriteria = IDL.Record({
  'offset' : IDL.Opt(IDL.Nat),
  'priceRange' : IDL.Opt(PriceRange),
  'limit' : IDL.Opt(IDL.Nat),
  'searchTerm' : IDL.Opt(IDL.Text),
  'sortOption' : ListingSortOption,
  'category' : IDL.Opt(IDL.Text),
  'condition' : IDL.Opt(ProductCondition),
});
export const RecommendationMode = IDL.Variant({
  'heuristic' : IDL.Null,
  'external' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'verified_student' : IDL.Bool,
  'onboarding_complete' : IDL.Bool,
  'star_rating' : IDL.Float64,
  'campus' : IDL.Text,
  'reliability_score' : IDL.Float64,
  'department' : IDL.Text,
  'hostel' : IDL.Text,
  'transaction_count' : IDL.Nat,
});
export const SellWizardDraft = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'updated_at' : Time,
  'description' : IDL.Text,
  'created_at' : Time,
  'meetup_locations' : IDL.Vec(LocationDetail),
  'defect_description' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'campus' : IDL.Text,
  'department' : IDL.Text,
  'original_price' : IDL.Opt(IDL.Nat32),
  'price' : IDL.Nat32,
  'hostel' : IDL.Text,
  'condition' : ProductCondition,
  'images' : IDL.Vec(ListingImage),
});
export const MostTradedCategoryAnalytics = IDL.Record({
  'topItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'sales' : IDL.Nat,
  'category' : IDL.Text,
});
export const InsightsAnalytics = IDL.Record({
  'mostPopularCategory' : IDL.Opt(IDL.Text),
  'mostTradedCategory' : IDL.Opt(MostTradedCategoryAnalytics),
});
export const NotificationType = IDL.Variant({
  'listing_sold' : IDL.Record({ 'listing_id' : IDL.Text }),
  'new_message' : IDL.Record({ 'listing_id' : IDL.Text }),
  'price_change' : IDL.Record({ 'listing_id' : IDL.Text }),
  'systemNotification' : IDL.Record({}),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'is_read' : IDL.Bool,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'notif_type' : NotificationType,
});
export const ProductReview = IDL.Record({
  'reviews' : IDL.Vec(Review),
  'seller' : IDL.Principal,
  'product_condition' : ProductCondition,
  'listing_id' : IDL.Text,
});
export const SellerReview = IDL.Record({
  'reviews' : IDL.Vec(Review),
  'seller' : IDL.Principal,
  'listing_id' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addListing' : IDL.Func([Listing], [], []),
  'addMessage' : IDL.Func([IDL.Text, Message], [], []),
  'addProductReview' : IDL.Func(
      [IDL.Text, IDL.Principal, Review, ProductCondition],
      [],
      [],
    ),
  'addSellerReview' : IDL.Func([IDL.Text, IDL.Principal, Review], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatThread' : IDL.Func([ChatThread], [], []),
  'createReport' : IDL.Func([Report], [], []),
  'deleteDraft' : IDL.Func([IDL.Text], [], []),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'fetchRecommendations' : IDL.Func(
      [RecommendationRequest],
      [IDL.Vec(Listing)],
      [],
    ),
  'filterAndSortListings' : IDL.Func(
      [SearchCriteria],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAIRecommendationMode' : IDL.Func([], [RecommendationMode], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatThread' : IDL.Func([IDL.Text], [IDL.Opt(ChatThread)], ['query']),
  'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
  'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(SellWizardDraft)], ['query']),
  'getDrafts' : IDL.Func([], [IDL.Vec(SellWizardDraft)], ['query']),
  'getInsightsAnalytics' : IDL.Func([], [InsightsAnalytics], ['query']),
  'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPersistentStorageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductReviews' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProductReview)],
      ['query'],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getSavedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getSellerReviews' : IDL.Func([IDL.Text], [IDL.Opt(SellerReview)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAIAssistEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isAIFeatureEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func([SellWizardDraft], [], []),
  'saveListing' : IDL.Func([IDL.Text], [], []),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'setAIFeatureEnabled' : IDL.Func([IDL.Bool], [], []),
  'setRecommendationMode' : IDL.Func([RecommendationMode], [], []),
  'unsaveListing' : IDL.Func([IDL.Text], [], []),
  'updateListing' : IDL.Func([IDL.Text, Listing], [], []),
  'updateReview' : IDL.Func([IDL.Text, IDL.Nat, Review, IDL.Bool], [], []),
  'updateTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'sold' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const SellerTrustIndicators = IDL.Record({
    'verified_student' : IDL.Bool,
    'star_rating' : IDL.Float64,
    'reliability_score' : IDL.Float64,
    'transaction_count' : IDL.Nat,
  });
  const LocationDetail = IDL.Record({
    'name' : IDL.Text,
    'location_type' : IDL.Variant({
      'dorm' : IDL.Null,
      'zone' : IDL.Null,
      'building' : IDL.Null,
      'meetupSpot' : IDL.Null,
    }),
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const ProductCondition = IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'likeNew' : IDL.Null,
    'wellUsed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingImage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'upload_status' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'updated_at' : Time,
    'trust_indicators' : SellerTrustIndicators,
    'description' : IDL.Text,
    'created_at' : Time,
    'seller' : IDL.Principal,
    'meetup_locations' : IDL.Vec(LocationDetail),
    'defect_description' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'campus' : IDL.Text,
    'department' : IDL.Text,
    'original_price' : IDL.Opt(IDL.Nat32),
    'price' : IDL.Nat32,
    'hostel' : IDL.Text,
    'condition' : ProductCondition,
    'images' : IDL.Vec(ListingImage),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'read_by_seller' : IDL.Bool,
    'read_by_buyer' : IDL.Bool,
    'timestamp' : Time,
  });
  const Review = IDL.Record({
    'created_at' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatThread = IDL.Record({
    'id' : IDL.Text,
    'is_blocked' : IDL.Bool,
    'is_muted' : IDL.Bool,
    'messages' : IDL.Vec(Message),
    'typing_buyer' : IDL.Bool,
    'seller' : IDL.Principal,
    'typing_seller' : IDL.Bool,
    'buyer' : IDL.Principal,
    'listing_id' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'timestamp' : Time,
    'listing_id' : IDL.Text,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const RecommendationType = IDL.Variant({
    'similarCategory' : IDL.Null,
    'trending' : IDL.Null,
    'collaborative' : IDL.Null,
    'personalized' : IDL.Null,
  });
  const RecommendationRequest = IDL.Record({
    'recType' : RecommendationType,
    'user' : IDL.Principal,
    'limit' : IDL.Nat,
    'externalPrompt' : IDL.Opt(IDL.Text),
    'contextListing' : IDL.Opt(Listing),
  });
  const PriceRange = IDL.Record({ 'max' : IDL.Nat32, 'min' : IDL.Nat32 });
  const ListingSortOption = IDL.Variant({
    'none' : IDL.Null,
    'priceLowToHigh' : IDL.Null,
    'distance' : IDL.Null,
    'newestFirst' : IDL.Null,
    'relevance' : IDL.Null,
    'priceHighToLow' : IDL.Null,
    'conditionQuality' : IDL.Null,
    'popularity' : IDL.Null,
  });
  const SearchCriteria = IDL.Record({
    'offset' : IDL.Opt(IDL.Nat),
    'priceRange' : IDL.Opt(PriceRange),
    'limit' : IDL.Opt(IDL.Nat),
    'searchTerm' : IDL.Opt(IDL.Text),
    'sortOption' : ListingSortOption,
    'category' : IDL.Opt(IDL.Text),
    'condition' : IDL.Opt(ProductCondition),
  });
  const RecommendationMode = IDL.Variant({
    'heuristic' : IDL.Null,
    'external' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'verified_student' : IDL.Bool,
    'onboarding_complete' : IDL.Bool,
    'star_rating' : IDL.Float64,
    'campus' : IDL.Text,
    'reliability_score' : IDL.Float64,
    'department' : IDL.Text,
    'hostel' : IDL.Text,
    'transaction_count' : IDL.Nat,
  });
  const SellWizardDraft = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'updated_at' : Time,
    'description' : IDL.Text,
    'created_at' : Time,
    'meetup_locations' : IDL.Vec(LocationDetail),
    'defect_description' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'campus' : IDL.Text,
    'department' : IDL.Text,
    'original_price' : IDL.Opt(IDL.Nat32),
    'price' : IDL.Nat32,
    'hostel' : IDL.Text,
    'condition' : ProductCondition,
    'images' : IDL.Vec(ListingImage),
  });
  const MostTradedCategoryAnalytics = IDL.Record({
    'topItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'sales' : IDL.Nat,
    'category' : IDL.Text,
  });
  const InsightsAnalytics = IDL.Record({
    'mostPopularCategory' : IDL.Opt(IDL.Text),
    'mostTradedCategory' : IDL.Opt(MostTradedCategoryAnalytics),
  });
  const NotificationType = IDL.Variant({
    'listing_sold' : IDL.Record({ 'listing_id' : IDL.Text }),
    'new_message' : IDL.Record({ 'listing_id' : IDL.Text }),
    'price_change' : IDL.Record({ 'listing_id' : IDL.Text }),
    'systemNotification' : IDL.Record({}),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'is_read' : IDL.Bool,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'notif_type' : NotificationType,
  });
  const ProductReview = IDL.Record({
    'reviews' : IDL.Vec(Review),
    'seller' : IDL.Principal,
    'product_condition' : ProductCondition,
    'listing_id' : IDL.Text,
  });
  const SellerReview = IDL.Record({
    'reviews' : IDL.Vec(Review),
    'seller' : IDL.Principal,
    'listing_id' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addListing' : IDL.Func([Listing], [], []),
    'addMessage' : IDL.Func([IDL.Text, Message], [], []),
    'addProductReview' : IDL.Func(
        [IDL.Text, IDL.Principal, Review, ProductCondition],
        [],
        [],
      ),
    'addSellerReview' : IDL.Func([IDL.Text, IDL.Principal, Review], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatThread' : IDL.Func([ChatThread], [], []),
    'createReport' : IDL.Func([Report], [], []),
    'deleteDraft' : IDL.Func([IDL.Text], [], []),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'fetchRecommendations' : IDL.Func(
        [RecommendationRequest],
        [IDL.Vec(Listing)],
        [],
      ),
    'filterAndSortListings' : IDL.Func(
        [SearchCriteria],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAIRecommendationMode' : IDL.Func([], [RecommendationMode], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatThread' : IDL.Func([IDL.Text], [IDL.Opt(ChatThread)], ['query']),
    'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
    'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(SellWizardDraft)], ['query']),
    'getDrafts' : IDL.Func([], [IDL.Vec(SellWizardDraft)], ['query']),
    'getInsightsAnalytics' : IDL.Func([], [InsightsAnalytics], ['query']),
    'getListing' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPersistentStorageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductReviews' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProductReview)],
        ['query'],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getSavedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getSellerReviews' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SellerReview)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAIAssistEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isAIFeatureEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func([SellWizardDraft], [], []),
    'saveListing' : IDL.Func([IDL.Text], [], []),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'setAIFeatureEnabled' : IDL.Func([IDL.Bool], [], []),
    'setRecommendationMode' : IDL.Func([RecommendationMode], [], []),
    'unsaveListing' : IDL.Func([IDL.Text], [], []),
    'updateListing' : IDL.Func([IDL.Text, Listing], [], []),
    'updateReview' : IDL.Func([IDL.Text, IDL.Nat, Review, IDL.Bool], [], []),
    'updateTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };