/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Listing {
    id: string;
    status: ListingStatus;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    seller: Principal;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: string;
    timestamp: Time;
    listing_id: string;
    reporter: Principal;
    reason: string;
}
export interface RecommendationResponse {
    recType: RecommendationType;
    source: RecommendationMode;
    listings: Array<Listing>;
}
export interface RecommendationRequest {
    recType: RecommendationType;
    user: Principal;
    limit: bigint;
    externalPrompt?: string;
    contextListing?: Listing;
}
export interface MostTradedCategoryAnalytics {
    topItems: Array<[string, bigint]>;
    sales: bigint;
    category: string;
}
export interface ListingImage {
    id: bigint;
    url: string;
    upload_status: string;
    blob?: ExternalBlob;
    name: string;
}
export type NotificationType = {
    __kind__: "listing_sold";
    listing_sold: {
        listing_id: string;
    };
} | {
    __kind__: "new_message";
    new_message: {
        listing_id: string;
    };
} | {
    __kind__: "price_change";
    price_change: {
        listing_id: string;
    };
} | {
    __kind__: "systemNotification";
    systemNotification: {
    };
};
export interface InsightsAnalytics {
    mostPopularCategory?: string;
    mostTradedCategory?: MostTradedCategoryAnalytics;
}
export interface ChatThread {
    id: string;
    is_blocked: boolean;
    is_muted: boolean;
    messages: Array<Message>;
    typing_buyer: boolean;
    seller: Principal;
    typing_seller: boolean;
    buyer: Principal;
    listing_id: string;
}
export interface SellWizardDraft {
    id: string;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}
export interface Notification {
    id: string;
    is_read: boolean;
    user: Principal;
    timestamp: Time;
    notif_type: NotificationType;
}
export interface Message {
    id: string;
    content: string;
    sender: Principal;
    read_by_seller: boolean;
    read_by_buyer: boolean;
    timestamp: Time;
}
export interface UserProfile {
    principal: Principal;
    onboarding_complete: boolean;
    campus: string;
    department: string;
    hostel: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ListingStatus {
    active = "active",
    sold = "sold",
    draft = "draft"
}
export enum RecommendationMode {
    heuristic = "heuristic",
    external = "external"
}
export enum RecommendationType {
    similarCategory = "similarCategory",
    trending = "trending",
    collaborative = "collaborative",
    personalized = "personalized"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addListing(listing: Listing): Promise<void>;
    addMessage(threadId: string, message: Message): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChatThread(thread: ChatThread): Promise<void>;
    createReport(report: Report): Promise<void>;
    deleteDraft(draftId: string): Promise<void>;
    deleteListing(listingId: string): Promise<void>;
    deleteReport(reportId: string): Promise<void>;
    fetchRecommendations(request: RecommendationRequest): Promise<RecommendationResponse>;
    getAIRecommendationMode(): Promise<RecommendationMode>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatThread(threadId: string): Promise<ChatThread | null>;
    getChatThreads(): Promise<Array<ChatThread>>;
    getDraft(draftId: string): Promise<SellWizardDraft | null>;
    getDrafts(): Promise<Array<SellWizardDraft>>;
    getInsightsAnalytics(): Promise<InsightsAnalytics>;
    getListing(listingId: string): Promise<Listing | null>;
    getListings(): Promise<Array<Listing>>;
    getListingsBySeller(seller: Principal): Promise<Array<Listing>>;
    getNotifications(): Promise<Array<Notification>>;
    getPersistentStorageCount(): Promise<bigint>;
    getReports(): Promise<Array<Report>>;
    getSavedListings(): Promise<Array<Listing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAIAssistEnabled(): Promise<boolean>;
    isAIFeatureEnabled(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDraft(draft: SellWizardDraft): Promise<void>;
    saveListing(listingId: string): Promise<void>;
    searchListings(searchTerm: string): Promise<Array<Listing>>;
    setAIFeatureEnabled(enabled: boolean): Promise<void>;
    setRecommendationMode(mode: RecommendationMode): Promise<void>;
    unsaveListing(listingId: string): Promise<void>;
    updateListing(listingId: string, updatedListing: Listing): Promise<void>;
    updateTypingStatus(threadId: string, isTyping: boolean): Promise<void>;
}
import type { ChatThread as _ChatThread, ExternalBlob as _ExternalBlob, InsightsAnalytics as _InsightsAnalytics, Listing as _Listing, ListingImage as _ListingImage, ListingStatus as _ListingStatus, MostTradedCategoryAnalytics as _MostTradedCategoryAnalytics, Notification as _Notification, NotificationType as _NotificationType, RecommendationMode as _RecommendationMode, RecommendationRequest as _RecommendationRequest, RecommendationResponse as _RecommendationResponse, RecommendationType as _RecommendationType, SellWizardDraft as _SellWizardDraft, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addListing(arg0: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(await to_candid_Listing_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(await to_candid_Listing_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMessage(arg0: string, arg1: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChatThread(arg0: ChatThread): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatThread(arg0);
            return result;
        }
    }
    async createReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0);
            return result;
        }
    }
    async deleteDraft(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraft(arg0);
            return result;
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async fetchRecommendations(arg0: RecommendationRequest): Promise<RecommendationResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchRecommendations(await to_candid_RecommendationRequest_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RecommendationResponse_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchRecommendations(await to_candid_RecommendationRequest_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RecommendationResponse_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAIRecommendationMode(): Promise<RecommendationMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIRecommendationMode();
                return from_candid_RecommendationMode_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIRecommendationMode();
            return from_candid_RecommendationMode_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatThread(arg0: string): Promise<ChatThread | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThread(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThread(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatThreads(): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThreads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThreads();
            return result;
        }
    }
    async getDraft(arg0: string): Promise<SellWizardDraft | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraft(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraft(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrafts(): Promise<Array<SellWizardDraft>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrafts();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrafts();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsightsAnalytics(): Promise<InsightsAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsightsAnalytics();
                return from_candid_InsightsAnalytics_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsightsAnalytics();
            return from_candid_InsightsAnalytics_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: string): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsBySeller(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsBySeller(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsBySeller(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersistentStorageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentStorageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentStorageCount();
            return result;
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async getSavedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedListings();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedListings();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAIAssistEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAIAssistEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAIAssistEnabled();
            return result;
        }
    }
    async isAIFeatureEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAIFeatureEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAIFeatureEnabled();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDraft(arg0: SellWizardDraft): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(await to_candid_SellWizardDraft_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(await to_candid_SellWizardDraft_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveListing(arg0);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAIFeatureEnabled(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAIFeatureEnabled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAIFeatureEnabled(arg0);
            return result;
        }
    }
    async setRecommendationMode(arg0: RecommendationMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRecommendationMode(to_candid_RecommendationMode_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRecommendationMode(to_candid_RecommendationMode_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unsaveListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveListing(arg0);
            return result;
        }
    }
    async updateListing(arg0: string, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, await to_candid_Listing_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, await to_candid_Listing_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTypingStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTypingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTypingStatus(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InsightsAnalytics_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsightsAnalytics): InsightsAnalytics {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ListingImage_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingImage): Promise<ListingImage> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationMode_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationMode): RecommendationMode {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_RecommendationResponse_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationResponse): Promise<RecommendationResponse> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationType): RecommendationType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_SellWizardDraft_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellWizardDraft): Promise<SellWizardDraft> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatThread]): ChatThread | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SellWizardDraft]): Promise<SellWizardDraft | null> {
    return value.length === 0 ? null : await from_candid_SellWizardDraft_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MostTradedCategoryAnalytics]): MostTradedCategoryAnalytics | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recType: _RecommendationType;
    source: _RecommendationMode;
    listings: Array<_Listing>;
}): Promise<{
    recType: RecommendationType;
    source: RecommendationMode;
    listings: Array<Listing>;
}> {
    return {
        recType: from_candid_RecommendationType_n24(_uploadFile, _downloadFile, value.recType),
        source: from_candid_RecommendationMode_n26(_uploadFile, _downloadFile, value.source),
        listings: await from_candid_vec_n28(_uploadFile, _downloadFile, value.listings)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ListingStatus;
    title: string;
    updated_at: _Time;
    description: string;
    created_at: _Time;
    seller: Principal;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<_ListingImage>;
}): Promise<{
    id: string;
    status: ListingStatus;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    seller: Principal;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n31(_uploadFile, _downloadFile, value.status),
        title: value.title,
        updated_at: value.updated_at,
        description: value.description,
        created_at: value.created_at,
        seller: value.seller,
        category: value.category,
        campus: value.campus,
        department: value.department,
        price: value.price,
        hostel: value.hostel,
        condition: value.condition,
        images: await from_candid_vec_n33(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    upload_status: string;
    blob: [] | [_ExternalBlob];
    name: string;
}): Promise<{
    id: bigint;
    url: string;
    upload_status: string;
    blob?: ExternalBlob;
    name: string;
}> {
    return {
        id: value.id,
        url: value.url,
        upload_status: value.upload_status,
        blob: record_opt_to_undefined(await from_candid_opt_n36(_uploadFile, _downloadFile, value.blob)),
        name: value.name
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    updated_at: _Time;
    description: string;
    created_at: _Time;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<_ListingImage>;
}): Promise<{
    id: string;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}> {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        description: value.description,
        created_at: value.created_at,
        category: value.category,
        campus: value.campus,
        department: value.department,
        price: value.price,
        hostel: value.hostel,
        condition: value.condition,
        images: await from_candid_vec_n33(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mostPopularCategory: [] | [string];
    mostTradedCategory: [] | [_MostTradedCategoryAnalytics];
}): {
    mostPopularCategory?: string;
    mostTradedCategory?: MostTradedCategoryAnalytics;
} {
    return {
        mostPopularCategory: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.mostPopularCategory)),
        mostTradedCategory: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.mostTradedCategory))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    is_read: boolean;
    user: Principal;
    timestamp: _Time;
    notif_type: _NotificationType;
}): {
    id: string;
    is_read: boolean;
    user: Principal;
    timestamp: Time;
    notif_type: NotificationType;
} {
    return {
        id: value.id,
        is_read: value.is_read,
        user: value.user,
        timestamp: value.timestamp,
        notif_type: from_candid_NotificationType_n54(_uploadFile, _downloadFile, value.notif_type)
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    similarCategory: null;
} | {
    trending: null;
} | {
    collaborative: null;
} | {
    personalized: null;
}): RecommendationType {
    return "similarCategory" in value ? RecommendationType.similarCategory : "trending" in value ? RecommendationType.trending : "collaborative" in value ? RecommendationType.collaborative : "personalized" in value ? RecommendationType.personalized : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heuristic: null;
} | {
    external: null;
}): RecommendationMode {
    return "heuristic" in value ? RecommendationMode.heuristic : "external" in value ? RecommendationMode.external : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    sold: null;
} | {
    draft: null;
}): ListingStatus {
    return "active" in value ? ListingStatus.active : "sold" in value ? ListingStatus.sold : "draft" in value ? ListingStatus.draft : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listing_sold: {
        listing_id: string;
    };
} | {
    new_message: {
        listing_id: string;
    };
} | {
    price_change: {
        listing_id: string;
    };
} | {
    systemNotification: {
    };
}): {
    __kind__: "listing_sold";
    listing_sold: {
        listing_id: string;
    };
} | {
    __kind__: "new_message";
    new_message: {
        listing_id: string;
    };
} | {
    __kind__: "price_change";
    price_change: {
        listing_id: string;
    };
} | {
    __kind__: "systemNotification";
    systemNotification: {
    };
} {
    return "listing_sold" in value ? {
        __kind__: "listing_sold",
        listing_sold: value.listing_sold
    } : "new_message" in value ? {
        __kind__: "new_message",
        new_message: value.new_message
    } : "price_change" in value ? {
        __kind__: "price_change",
        price_change: value.price_change
    } : "systemNotification" in value ? {
        __kind__: "systemNotification",
        systemNotification: value.systemNotification
    } : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n29(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ListingImage>): Promise<Array<ListingImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ListingImage_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SellWizardDraft>): Promise<Array<SellWizardDraft>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SellWizardDraft_n43(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n52(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ListingImage_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingImage): Promise<_ListingImage> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_Listing_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_RecommendationMode_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationMode): _RecommendationMode {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_RecommendationRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationRequest): Promise<_RecommendationRequest> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RecommendationType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationType): _RecommendationType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_SellWizardDraft_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellWizardDraft): Promise<_SellWizardDraft> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    upload_status: string;
    blob?: ExternalBlob;
    name: string;
}): Promise<{
    id: bigint;
    url: string;
    upload_status: string;
    blob: [] | [_ExternalBlob];
    name: string;
}> {
    return {
        id: value.id,
        url: value.url,
        upload_status: value.upload_status,
        blob: value.blob ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.blob)) : candid_none(),
        name: value.name
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recType: RecommendationType;
    user: Principal;
    limit: bigint;
    externalPrompt?: string;
    contextListing?: Listing;
}): Promise<{
    recType: _RecommendationType;
    user: Principal;
    limit: bigint;
    externalPrompt: [] | [string];
    contextListing: [] | [_Listing];
}> {
    return {
        recType: to_candid_RecommendationType_n20(_uploadFile, _downloadFile, value.recType),
        user: value.user,
        limit: value.limit,
        externalPrompt: value.externalPrompt ? candid_some(value.externalPrompt) : candid_none(),
        contextListing: value.contextListing ? candid_some(await to_candid_Listing_n8(_uploadFile, _downloadFile, value.contextListing)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}): Promise<{
    id: string;
    title: string;
    updated_at: _Time;
    description: string;
    created_at: _Time;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<_ListingImage>;
}> {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        description: value.description,
        created_at: value.created_at,
        category: value.category,
        campus: value.campus,
        department: value.department,
        price: value.price,
        hostel: value.hostel,
        condition: value.condition,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ListingStatus;
    title: string;
    updated_at: Time;
    description: string;
    created_at: Time;
    seller: Principal;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<ListingImage>;
}): Promise<{
    id: string;
    status: _ListingStatus;
    title: string;
    updated_at: _Time;
    description: string;
    created_at: _Time;
    seller: Principal;
    category: string;
    campus: string;
    department: string;
    price: number;
    hostel: string;
    condition: string;
    images: Array<_ListingImage>;
}> {
    return {
        id: value.id,
        status: to_candid_ListingStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        updated_at: value.updated_at,
        description: value.description,
        created_at: value.created_at,
        seller: value.seller,
        category: value.category,
        campus: value.campus,
        department: value.department,
        price: value.price,
        hostel: value.hostel,
        condition: value.condition,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    active: null;
} | {
    sold: null;
} | {
    draft: null;
} {
    return value == ListingStatus.active ? {
        active: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value == ListingStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationType): {
    similarCategory: null;
} | {
    trending: null;
} | {
    collaborative: null;
} | {
    personalized: null;
} {
    return value == RecommendationType.similarCategory ? {
        similarCategory: null
    } : value == RecommendationType.trending ? {
        trending: null
    } : value == RecommendationType.collaborative ? {
        collaborative: null
    } : value == RecommendationType.personalized ? {
        personalized: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationMode): {
    heuristic: null;
} | {
    external: null;
} {
    return value == RecommendationMode.heuristic ? {
        heuristic: null
    } : value == RecommendationMode.external ? {
        external: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ListingImage>): Promise<Array<_ListingImage>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ListingImage_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
